#!/usr/bin/python
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# i2cget.py
#
# Retrieve raw ADC value from temp sensor on ECE XMEGA expansion  board
# 
# Expansion Board I2C Address: 0x41 (sudo i2cdetect -y 1)
#
# AUTHOR: Jordan Millington

import smbus
import time
bus = smbus.SMBus(1)	# 1 = /dev/i2c-1

addr = 0x41
reg = 0x00

#for y in range(0,30):
#	for x in range(0,50):
#		data = bus.read_byte_data(addr,x)
#		print data,
#	print 
#	time.sleep(1)
data = long[] bus.read_block_data(addr,reg)
print data
