#!/usr/bin/python
a=[]
b=[1,2,3,4,5,6,7,8,9]
print b[3]
# print by index - last not inclusive
#print b[0:3]
print b[0:8:2] # 0-8 index - every second element
#[-1] is the last element
print b[-3:]
print b[7:-1]
